### ISSUE TITLE
Update README.md - note Kali's base OS

### ISSUE THREAD

**Issue by frozenstruct** [Double2Sky/OffenOsint#1]
Perhaps it would be more convenient to users to be able to quickly grasp what base OS they should select in VBox.

Cheers ~ 🐦

**Comment by frozenstruct** [comment]
AFAIK Kali uses Debian as base OS...

**Comment by Double2Sky** [comment]
The machine represents the full-fledged operating system packed in the file of the ova format. To click everything that it is necessary for the successful beginning of operation twice the file and to unpack to the convenient place. after unpacking to click start. 
Machine build on Kali linux / debian distro.

**Comment by frozenstruct** [comment]
Oh, my bad, sry.
